### ISSUE TITLE
Using `body_test_motion` without the `result` parameter causes a crash

### ISSUE THREAD

**Issue by KuroiRoy** [godot-jolt/godot-jolt#499]
Godot-Jolt is working well in my project since support for Godot 4.1 was added. Except when using my custom step-up function in my character controller, then it crashes immediately.

I have created an MRP (or MRE?) here: https://github.com/KuroiRoy/GodotJoltCrashMRP

The issue occurs immediately when starting the Game.tscn scene. Godot gives no debug information whatsoever about the crash. Fortunately Rider does. 
On [line 127 of KinematicCharacterController.cs](https://github.com/KuroiRoy/GodotJoltCrashMRP/blob/ef8a18b8551f2797fa16c5349049dd91e3d3a265/Scripts/Players/KinematicCharacterController.cs#L127) the following error occurs:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr, IntPtr, Void**, Void*)
   at Godot.NativeCalls.godot_icall_3_749(IntPtr, IntPtr, Godot.Rid, IntPtr, IntPtr)
   at Godot.PhysicsServer3D.BodyTestMotion(Godot.Rid, Godot.PhysicsTestMotionParameters3D, Godot.PhysicsTestMotionResult3D)
   at GodotJoltCrashMRP.Scripts.Players.KinematicCharacterController.StepUp(Single)
   at GodotJoltCrashMRP.Scripts.Players.KinematicCharacterController._PhysicsProcess(Double)
   at Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Godot.Node3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Godot.CollisionObject3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Godot.PhysicsBody3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Godot.CharacterBody3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at GodotJoltCrashMRP.Scripts.Players.KinematicCharacterController.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_variant**, Int32, Godot.NativeInterop.godot_variant_call_error*, Godot.NativeInterop.godot_variant*)
```

**Comment by mihe** [comment]
It seems I forgot to take into account that the `result` parameter to `BodyTestMotion` is optional, so I am accessing a null pointer if you omit that parameter, leading to the crash you're seeing.

I'll fix that right away, but in the meantime you can just pass a `PhysicsTestMotionResult3D` to it and it should work just fine.

**Comment by KuroiRoy** [comment]
Oh right, that's the only one that doesn't use the result parameter! I didn't get what was null. 

That fixes it, thank you!
